title: Dev Dump Logs
description: Relevance. Depth. ...........Random
permalink: ':title/'
baseurl: "" 
url: ""

# About Settings
author: Gabriel Ian Escober Abel
blog: dev dump logs
blog-img: logo.png
about: >
  Relevance. </br> 
  Depth. </br>
  ........... Random
author: Gabriel Ian E. Abel
social-twitter: _IanEscober
social-github: IanEscober
social-linkedin: IanEscober
social-email: gabrielabel_69@yahoo.com

# Disqus
discus-identifier: 

# Tracker
analytics: 

# Build Settings
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 7
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
